name: MCP Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed Python files
        id: files
        run: |
          echo "FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.py$' | xargs)" >> $GITHUB_ENV

      - name: Run MCP review
        env:
          FILES: ${{ env.FILES }}
        run: |
          if [ -z "$FILES" ]; then
            echo "No Python files to review." > mcp_review.txt
          else
            for file in $FILES; do
              CODE=$(cat "$file")
              RESPONSE=$(curl -s -X POST http://localhost:8000/call_tool \
                -H "Content-Type: application/json" \
                -d "{\"name\": \"review-pr\", \"arguments\": {\"code\": \"$CODE\"}}")
              echo "$RESPONSE" >> mcp_review.txt
            done
          fi

      - name: Post review as PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="MCP Code Review Results:\n$(cat mcp_review.txt)"
          gh issue comment ${{ github.event.pull_request.number }} --body "$COMMENT"
